# Generated by Django 4.2.7 on 2023-11-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product',
            new_name='products',
        ),
    ]
